# Generated by Django 6.0 on 2025-12-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название корпуса')),
                ('code', models.CharField(blank=True, help_text='Например: Гл, А, Б, ИИТ и т.п.', max_length=50, verbose_name='Код корпуса')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('lat', models.FloatField(help_text='Для отображения на карте', verbose_name='Широта')),
                ('lng', models.FloatField(help_text='Для отображения на карте', verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('type', models.CharField(help_text='Например: столовая, деканат, вход, туалет', max_length=50, verbose_name='Тип')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('info', models.TextField(blank=True, verbose_name='Доп. информация')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='campus.building', verbose_name='Корпус')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер аудитории')),
                ('floor', models.IntegerField(default=1, verbose_name='Этаж')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='campus.building', verbose_name='Корпус')),
            ],
        ),
    ]
